---
name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    name: pre-commit / Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0
