name: Test code and lint

on:
  pull_request:
  push:
  schedule:
    - cron: 0 2 * * * # run at 2 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.10.0
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: run tests
        run: |
          pip install .
          sudo apt install klayout
          cd tests
          bash run_tests.sh
